# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PrytOYwh62G0pfWDMHsRW1gapaX6uyut

Project : **Amazon superstore Data Analysis**



  Name of the task : Exploratory Data Analysis- (Retail)

  Task category : Data science and Business Analytics

###**Objective** : to find out the weak areas where the amazons business manager can work to make more profit or increase sales and deriving the business problem by exploring the data.

# steps involved

*   defining the problem
*   checking versions of libraries


*   importing libraries into this notebook
*   importing dataset


*   cleaning of data - preprocessing of data
*   summarizing datasets to extract actionable insights


*   visualization of data
*   conclusion

# version verifications of library
"""

import numpy
print('numpy: {}'. format(numpy.__version__))
import matplotlib
print('matplotlib: {}'. format(matplotlib.__version__))
import pandas
print('pandas: {}'. format(pandas.__version__))

"""# importing libraries"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import datasets
from matplotlib import pyplot
from pandas.plotting import scatter_matrix
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
import os

print("libraries imported successfully!!")

"""# reading dataset"""

df1 =pd.read_csv("SampleSuperstore.csv")

"""# pre-processing of data & exploratory data analysis

dimensions of data
"""

df1.shape

"""peek at the data

"""

df1.head()

df1.tail()

"""columns in data

"""

df1.columns

"""category types in data"""

df1["Category"].unique()

"""types of sub category"""

df1["Sub-Category"].unique()

"""types of segment"""

df1['Segment'].unique()

"""dropping of postal code column"""

df1=df1.drop(columns=["Postal Code"], axis=1)

df1.head()

"""number of products in each category"""

df1["Category"].value_counts()

df1["Category"].count()

"""number of sub categories products are divided"""

df1['Sub-Category'].nunique()

"""number of products in each sub-categories

"""

df1["Sub-Category"].value_counts()

"""types of region"""

df1['Region'].unique()

"""types of shipmode"""

df1['Ship Mode'].unique()

"""unique states"""

df1['State'].unique()

"""unique cities"""

df1['City'].unique()

"""number of unique values in each column"""

df1.nunique()

"""fukk summary of data"""

df1.info()

"""statistical summary of data"""

df1.describe()

"""total null values in data"""

df1.isnull().sum()

"""data types"""

df1.dtypes

"""unique data in each column"""

for col in df1:
  print(df1[col].unique())

"""number of duplicate values in data"""

df1.duplicated().sum()

"""dropping of duplicate values"""

df1.drop_duplicates()

"""correlation among the columns"""

df1.corr()

"""covariance between set of functions"""

df1.cov()

"""slicing of data"""

df1.iloc[0:3]

"""# visualization of data

bar plot between sub category by category
"""

plt.figure(figsize=(20,10))
plt.bar('Sub-Category', 'Category', data=df1)
plt.show()

"""pie plot of sub categories"""

plt.figure(figsize=(7,7))
df1['Sub-Category'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title("sub-categories")
plt.show()

"""Bar plot of sales vs profit"""

df1.groupby('Sub-Category')['Profit','Sales'].agg(['sum']).plot.bar()
plt.title('total profit and sales per sub-category')
plt.show()

"""# results

1.   highest profit earned is copiers and sales are high for chairs and phones
2.   fact- people don't prefer to buy tables and bookcases from superstores as they are in loss

count plot of cities
"""

plt.figure(figsize=(15,8))
sns.countplot(x=df1['State'])
plt.xticks(rotation=90)

"""sales and profit region wise"""

df1.groupby('Region')['Profit','Sales'].agg(['sum']).plot.bar()
plt.title("total profit and sales by region")

"""count plot of sub categories"""

print(df1["Sub-Category"].value_counts())
plt.figure(figsize=(12,6))
sns.countplot(x=df1['Sub-Category'])
plt.xticks(rotation=90)
plt.show()

"""heatmap of correlation among the columns"""

fig,axes=plt.subplots(1,1,figsize=(9,6))
sns.heatmap(df1.corr(),annot=True)

"""histogram of data"""

df1.hist(bins=50, figsize=(20,15))

"""pair plot of subcategory"""

figsize=(15,10)
sns.pairplot(df1,hue='Sub-Category')

"""box plot of sales, quantity, discount, profit"""

df1.plot(kind='box', subplots=True , layout=(3,2),sharex= False, sharey=False)
plt.rcParams['figure.figsize']=[20,12]
plt.show

"""# conclusion

1. profit in south and central is less
2. profit in east and west region is better
3. highest profit is earned in copiers while selling price for chairs and phones are extremely high
4. intresting fact- people dont prefer buying tables and bookcases from superstore
5. the store has wide variety of office supplies
6. there is negative correlation between profit and discount
7. total sum of profit in sale of table is negative
8. profit is more in sales of copiers
9. very less profit in sale of supplies
10. technology segment is more profitable

# Thank you
"""